/**
 * OpenAI-compatible LLM adapter.
 *
 * Calls an OpenAI-compatible /chat/completions endpoint using
 * per-request credentials from req.llmConfig (or server-side
 * environment defaults).  Prompts are generated by prompts.js.
 *
 * Returns the same { status, sections, warnings } shape as the
 * mock models so the adapter can be swapped transparently.
 */

import { config } from '../config.js';
import { getLogger } from '../logger.js';
import {
  buildExplainPrompt,
  buildSimplifyPrompt,
  buildDefinePrompt,
  buildFigurePrompt,
  buildFollowUpPrompt,
  buildSummarizePrompt,
  buildChunkSummarizePrompt,
  buildFinalSynthesisPrompt,
} from './prompts.js';

// ── Vision-capable model detection ────────────────────────────

const VISION_MODELS = [
  'gpt-4o',
  'gpt-4o-mini',
  'gpt-4-vision',
  'gpt-4-turbo',
  'claude-3',
  'claude-3.5',
  'gemini-1.5',
  'gemini-2',
  'kimi-k2.5',
  'kimi-k2.6',
  'kimi-k2.7-code',
  'kimi-k2.7-code-highspeed',
  'kimi-k3',
  'moonshot-v1-8k-vision',
  'moonshot-v1-32k-vision',
  'moonshot-v1-128k-vision',
];

/**
 * Check whether a model name indicates vision capability.
 * @param {string} model
 * @returns {boolean}
 */
function supportsVision(model) {
  if (!model) {
    return false;
  }
  const lower = model.toLowerCase();
  return VISION_MODELS.some(v => lower.includes(v));
}

// ── Config resolution ──────────────────────────────────────────

/**
 * Merge per-request llmConfig over server-side defaults.
 * @param {Object|null} llmConfig — from req.llmConfig (middleware)
 * @returns {{ baseUrl: string|null, apiKey: string|null, model: string, language: string }}
 */
function resolveConfig(llmConfig) {
  return {
    baseUrl: llmConfig?.baseUrl || config.llm.defaultBaseUrl,
    apiKey: llmConfig?.apiKey || config.llm.defaultApiKey,
    model: llmConfig?.model || config.llm.defaultModel,
    language: llmConfig?.language || 'en',
  };
}

function createAdapterError(code, message, retryable) {
  return {
    status: 'error',
    sections: [],
    warnings: [{ code, message }],
    error: {
      code,
      message,
      retryable: !!retryable,
    },
  };
}

function createAdapterErrorFromException(err, fallbackMessage) {
  if (err && err.name === 'AbortError') {
    return createAdapterError('TIMEOUT', 'The LLM provider request timed out.', true);
  }

  return createAdapterError(
    'UPSTREAM_MODEL_ERROR',
    (err && err.message) || fallbackMessage || 'The LLM provider request failed.',
    true
  );
}

// ── LLM API call ───────────────────────────────────────────────

/**
 * Call an OpenAI-compatible /chat/completions endpoint.
 *
 * @param {Object} opts
 * @param {string} opts.baseUrl
 * @param {string|null} opts.apiKey
 * @param {string} opts.model
 * @param {Array} opts.messages — OpenAI messages array
 * @returns {Promise<string>} — raw content string from choices[0].message.content
 */
async function callCompletions({ baseUrl, apiKey, model, messages }) {
  const url = `${baseUrl}/chat/completions`;
  const headers = { 'Content-Type': 'application/json' };
  if (apiKey) {
    headers['Authorization'] = `Bearer ${apiKey}`;
  }

  const body = JSON.stringify({
    model,
    messages,
    // Do not force a temperature. Some OpenAI-compatible models only
    // accept their provider default (for example, Kimi K2.6 requires 1).
    max_tokens: 2000,
    response_format: { type: 'json_object' },
  });

  const retryableStatuses = new Set([429, 502, 503, 504]);
  const maxRetries = Math.max(0, config.llm.maxRetries || 0);

  function isRetryableDetail(detail) {
    return /overload|try again|rate.?limit|temporar(?:y|ily)|unavailable/i.test(detail || '');
  }

  function retryDelayMs(res, attempt) {
    const retryAfterHeader = res?.headers?.get?.('retry-after');
    const retryAfter = retryAfterHeader ? Number(retryAfterHeader) : NaN;
    if (Number.isFinite(retryAfter) && retryAfter >= 0) {
      return Math.min(retryAfter * 1000, 5000);
    }
    const base = Math.max(100, config.llm.retryBaseMs || 750);
    return Math.min(base * 2 ** attempt + Math.round(Math.random() * 250), 5000);
  }

  function wait(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  for (let attempt = 0; attempt <= maxRetries; attempt += 1) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), config.llm.timeoutMs);

    try {
      const res = await fetch(url, {
        method: 'POST',
        headers,
        body,
        signal: controller.signal,
      });

      if (!res.ok) {
        let detail = `HTTP ${res.status}`;
        try {
          const errBody = await res.json();
          if (errBody?.error?.message) {
            detail = errBody.error.message;
          }
        } catch {
          // non-JSON error body
        }

        const canRetry =
          attempt < maxRetries &&
          (retryableStatuses.has(res.status) || isRetryableDetail(detail));
        if (canRetry) {
          const delayMs = retryDelayMs(res, attempt);
          getLogger().warn(
            { model, statusCode: res.status, attempt: attempt + 1, delayMs },
            'LLM provider temporarily unavailable; retrying'
          );
          await wait(delayMs);
          continue;
        }

        throw new Error(`LLM API error: ${detail}`);
      }

      const data = await res.json();
      const content = data?.choices?.[0]?.message?.content;
      if (!content) {
        throw new Error('LLM API returned empty content');
      }
      return content;
    } finally {
      clearTimeout(timer);
    }
  }

  throw new Error('LLM API request failed after retries');
}

// ── JSON response parsing with fallback ─────────────────────────

/**
 * Parse LLM response text into sections array.
 * Attempts JSON.parse, then markdown code block extraction,
 * then falls back to wrapping the entire text in one section.
 *
 * @param {string} raw — raw content from LLM
 * @returns {{ sections: Array<{title: string, content: string}>, warnings: Array<{code: string, message: string}> }}
 */
function parseSections(raw) {
  const warnings = [];

  // 1. Direct JSON.parse
  try {
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed.sections) && parsed.sections.length > 0) {
      return { sections: parsed.sections, warnings };
    }
  } catch {
    // fall through
  }

  // 2. Extract from markdown code block: ```json ... ```
  const codeBlockMatch = raw.match(/```(?:json)?\s*\n?([\s\S]*?)\n?```/);
  if (codeBlockMatch) {
    try {
      const parsed = JSON.parse(codeBlockMatch[1].trim());
      if (Array.isArray(parsed.sections) && parsed.sections.length > 0) {
        return { sections: parsed.sections, warnings };
      }
    } catch {
      // fall through
    }
  }

  // 3. Try to find a top-level JSON object with "sections" key anywhere
  const jsonMatch = raw.match(/\{[\s\S]*"sections"[\s\S]*\}/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[0]);
      if (Array.isArray(parsed.sections) && parsed.sections.length > 0) {
        return { sections: parsed.sections, warnings };
      }
    } catch {
      // fall through
    }
  }

  // 4. Fallback: wrap entire text as single section
  warnings.push({
    code: 'PARSE_FALLBACK',
    message: 'Could not parse structured JSON from LLM response. Displaying raw text instead.',
  });

  return {
    sections: [{ title: 'Response', content: raw.trim() }],
    warnings,
  };
}

// ── Build OpenAI messages array ──────────────────────────────────

/**
 * Build messages array from prompt system + user strings.
 * For figure requests with image data, use multimodal content format.
 */
function buildMessages(system, user, imageData) {
  const messages = [{ role: 'system', content: system }];

  if (imageData && imageData.dataUrl) {
    // Multimodal: text + image_url
    messages.push({
      role: 'user',
      content: [
        {
          type: 'image_url',
          image_url: { url: imageData.dataUrl },
        },
        { type: 'text', text: user },
      ],
    });
  } else {
    messages.push({ role: 'user', content: user });
  }

  return messages;
}

// ── Public API ───────────────────────────────────────────────────

/**
 * Text explanation via OpenAI-compatible LLM.
 *
 * @param {Object} input
 * @param {string} input.action — "explain" | "simplify" | "define"
 * @param {string} input.text
 * @param {string} [input.context]
 * @param {string} [input.paperTitle]
 * @param {Object} [input.llmConfig]
 * @returns {Promise<{status: string, sections: Array, warnings: Array}>}
 */
export async function explainText(input) {
  const cfg = resolveConfig(input.llmConfig);

  if (!cfg.baseUrl) {
    return createAdapterError('INVALID_REQUEST', 'No LLM base URL configured.', false);
  }

  const promptArgs = {
    text: input.text,
    context: input.context,
    paperTitle: input.paperTitle,
    language: cfg.language,
  };

  let prompt;
  switch (input.action) {
    case 'simplify':
      prompt = buildSimplifyPrompt(promptArgs);
      break;
    case 'define':
      prompt = buildDefinePrompt(promptArgs);
      break;
    default:
      prompt = buildExplainPrompt(promptArgs);
  }

  const messages = buildMessages(prompt.system, prompt.user);

  try {
    getLogger().info(
      { model: cfg.model, action: input.action, language: cfg.language },
      'Calling LLM for explainText'
    );
    const raw = await callCompletions({
      baseUrl: cfg.baseUrl,
      apiKey: cfg.apiKey,
      model: cfg.model,
      messages,
    });
    const result = parseSections(raw);
    return { status: 'success', ...result };
  } catch (err) {
    getLogger().error({ err: err.message }, 'LLM explainText failed');
    return createAdapterErrorFromException(err, 'LLM explainText failed.');
  }
}

/**
 * Figure explanation via OpenAI-compatible LLM (with optional vision).
 *
 * @param {Object} input
 * @param {string} [input.imageRef]
 * @param {{mimeType: string, dataUrl: string}} [input.imageData]
 * @param {string} [input.caption]
 * @param {string} [input.paperTitle]
 * @param {Object} [input.llmConfig]
 * @returns {Promise<{status: string, sections: Array, warnings: Array}>}
 */
export async function explainFigure(input) {
  const cfg = resolveConfig(input.llmConfig);

  if (!cfg.baseUrl) {
    return createAdapterError('INVALID_REQUEST', 'No LLM base URL configured.', false);
  }

  const hasImage = !!(input.imageData?.dataUrl && supportsVision(cfg.model));

  const prompt = buildFigurePrompt({
    caption: input.caption,
    paperTitle: input.paperTitle,
    hasImage,
    language: cfg.language,
  });

  const imageData = hasImage ? input.imageData : null;
  const messages = buildMessages(prompt.system, prompt.user, imageData);

  const warnings = [];
  if (input.imageData?.dataUrl && !supportsVision(cfg.model)) {
    warnings.push({
      code: 'NO_VISION_SUPPORT',
      message: `Model "${cfg.model}" may not support image analysis. Falling back to caption-only explanation.`,
    });
  }

  try {
    getLogger().info(
      { model: cfg.model, hasImage, language: cfg.language },
      'Calling LLM for explainFigure'
    );
    const raw = await callCompletions({
      baseUrl: cfg.baseUrl,
      apiKey: cfg.apiKey,
      model: cfg.model,
      messages,
    });
    const result = parseSections(raw);
    return {
      status: result.warnings.length > 0 || warnings.length > 0 ? 'partial_success' : 'success',
      sections: result.sections,
      warnings: [...warnings, ...result.warnings],
    };
  } catch (err) {
    getLogger().error({ err: err.message }, 'LLM explainFigure failed');
    return createAdapterErrorFromException(err, 'LLM explainFigure failed.');
  }
}

/**
 * Follow-up question via OpenAI-compatible LLM.
 *
 * @param {Object} input
 * @param {string} input.question
 * @param {string} [input.originalText]
 * @param {Array} [input.previousResults]
 * @param {Object} [input.llmConfig]
 * @returns {Promise<{status: string, sections: Array, warnings: Array}>}
 */
export async function followUp(input) {
  const cfg = resolveConfig(input.llmConfig);

  if (!cfg.baseUrl) {
    return createAdapterError('INVALID_REQUEST', 'No LLM base URL configured.', false);
  }

  const prompt = buildFollowUpPrompt({
    question: input.question,
    originalText: input.originalText,
    previousResults: input.previousResults,
    language: cfg.language,
  });

  const messages = buildMessages(prompt.system, prompt.user);

  try {
    getLogger().info({ model: cfg.model, language: cfg.language }, 'Calling LLM for followUp');
    const raw = await callCompletions({
      baseUrl: cfg.baseUrl,
      apiKey: cfg.apiKey,
      model: cfg.model,
      messages,
    });
    const result = parseSections(raw);
    return { status: 'success', ...result };
  } catch (err) {
    getLogger().error({ err: err.message }, 'LLM followUp failed');
    return createAdapterErrorFromException(err, 'LLM followUp failed.');
  }
}

// ── Summarize Document ───────────────────────────────────────────

/**
 * Summarize an entire document via OpenAI-compatible LLM.
 *
 * Supports two modes:
 *   - Direct: markdownText fits in one call (≤ chunkThreshold)
 *   - Chunked map-reduce: split into chunks, summarize each, then synthesize
 *
 * @param {Object} input
 * @param {string} input.markdownText — the full document text (already converted)
 * @param {string} [input.paperTitle]
 * @param {Object} [input.llmConfig]
 * @returns {Promise<{status: string, sections: Array, warnings: Array}>}
 */
export async function summarizeDocument(input) {
  const cfg = resolveConfig(input.llmConfig);

  if (!cfg.baseUrl) {
    return createAdapterError('INVALID_REQUEST', 'No LLM base URL configured.', false);
  }

  const text = input.markdownText || '';
  const warnings = [];
  const model = config.summarize.model || cfg.model;

  getLogger().info(
    {
      model,
      textLength: text.length,
      chunkThreshold: config.summarize.chunkThreshold,
      language: cfg.language,
    },
    'summarizeDocument start'
  );

  // Direct summarize — text fits within threshold
  if (text.length <= config.summarize.chunkThreshold) {
    const prompt = buildSummarizePrompt({
      markdownText: text,
      paperTitle: input.paperTitle,
      language: cfg.language,
    });
    const messages = buildMessages(prompt.system, prompt.user);

    try {
      getLogger().info({ model }, 'Calling LLM for summarizeDocument (direct)');
      const raw = await callCompletions({
        baseUrl: cfg.baseUrl,
        apiKey: cfg.apiKey,
        model,
        messages,
      });
      const result = parseSections(raw);
      return { status: 'success', ...result };
    } catch (err) {
      getLogger().error({ err: err.message }, 'LLM summarizeDocument failed');
      return createAdapterErrorFromException(err, 'LLM summarizeDocument failed.');
    }
  }

  // Map-reduce: split into chunks and summarize
  const chunkSize = config.summarize.chunkSize;
  const chunks = splitIntoChunks(text, chunkSize);

  getLogger().info(
    { chunkCount: chunks.length, chunkSize },
    'summarizeDocument: splitting into chunks'
  );

  // Map phase — summarize each chunk in parallel
  const chunkSummaries = await Promise.all(
    chunks.map(async (chunkText, index) => {
      const prompt = buildChunkSummarizePrompt({
        chunkText,
        chunkIndex: index,
        totalChunks: chunks.length,
        paperTitle: input.paperTitle,
        language: cfg.language,
      });
      const messages = buildMessages(prompt.system, prompt.user);

      try {
        getLogger().info(
          { model, chunkIndex: index, totalChunks: chunks.length },
          'Calling LLM for chunk summary'
        );
        const raw = await callCompletions({
          baseUrl: cfg.baseUrl,
          apiKey: cfg.apiKey,
          model,
          messages,
        });
        const result = parseSections(raw);
        return (result.sections || []).map(s => s.content || s.title || '').join(' ');
      } catch (err) {
        getLogger().warn(
          { err: err.message, chunkIndex: index },
          'Chunk summarization failed, using placeholder'
        );
        warnings.push({
          code: 'CHUNK_FAILED',
          message: `Part ${index + 1} could not be summarized.`,
        });
        return `[Part ${index + 1}: summarization unavailable]`;
      }
    })
  );

  // Reduce phase — synthesize chunk summaries
  const synthesisPrompt = buildFinalSynthesisPrompt({
    chunkSummaries,
    paperTitle: input.paperTitle,
    language: cfg.language,
  });
  const messages = buildMessages(synthesisPrompt.system, synthesisPrompt.user);

  try {
    getLogger().info({ model }, 'Calling LLM for final synthesis');
    const raw = await callCompletions({
      baseUrl: cfg.baseUrl,
      apiKey: cfg.apiKey,
      model,
      messages,
    });
    const result = parseSections(raw);
    return {
      status: warnings.length > 0 ? 'partial_success' : 'success',
      sections: result.sections,
      warnings: [...warnings, ...result.warnings],
    };
  } catch (err) {
    getLogger().error({ err: err.message }, 'LLM synthesis failed');
    return createAdapterErrorFromException(err, 'LLM synthesis failed.');
  }
}

/**
 * Split text into chunks, trying to break at paragraph boundaries.
 * @param {string} text
 * @param {number} chunkSize
 * @returns {string[]}
 */
function splitIntoChunks(text, chunkSize) {
  if (!text || text.length <= chunkSize) {
    return [text || ''];
  }

  const chunks = [];
  let remaining = text;

  while (remaining.length > 0) {
    if (remaining.length <= chunkSize) {
      chunks.push(remaining);
      break;
    }

    // Try to break at paragraph boundary
    let breakPoint = remaining.lastIndexOf('\n\n', chunkSize);
    if (breakPoint < chunkSize * 0.3) {
      // Try sentence boundary
      breakPoint = remaining.lastIndexOf('. ', chunkSize);
    }
    if (breakPoint < chunkSize * 0.3) {
      // Hard break
      breakPoint = chunkSize;
    }

    chunks.push(remaining.slice(0, breakPoint + 1));
    remaining = remaining.slice(breakPoint + 1);
  }

  return chunks;
}
